# Generated by Django 3.0.6 on 2020-05-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('category', models.CharField(choices=[('CRYPTO_CURRENCY', 'CryptoCurrency'), ('PRECIOUS_METAL', 'PreciousMetal'), ('STOCK', 'Stock')], max_length=64)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
